spring.application.name=adocao_pets

# Definindo a porta -> 8080 (caso tenha erro, mudar aqui)
server.port=8080

# Caminho de conexao do DB
spring.datasource.url=jdbc:postgresql://localhost:5432/ong_adocao_animais

# Long-in ao DB
spring.datasource.username=postgres
spring.datasource.password=1234

# Comando para mostrar no terminal os comandos SQLs
spring.jpa.show-sql=true

# Config hibernate de atualização constante
spring.jpa.hibernate.ddl-auto=update

# Converte os comandos resumidos do DB para hibernate que estão sendo usados 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Evita que qualquer parâmetro não declarado que foi passado no JSON seja ignorado.
spring.jackson.deserialization.fail-on-unknown-properties=false

# Evita o retorno de informações detalhadas do DB para o usuários da API
spring.web.error.include-stacktrace=never